parameters:
  varFile: ''
  environment: ''
  backendArg: ''
  azureSubscription: ''
  rootFolder: ''
  artifactName: 'plan'
  pool: 
    name: 'ubuntu'
jobs:
- deployment: destroy
  displayName: Terraform Destroy
  pool: ${{ parameters.pool }}
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - template: get-tf-credentials.steps.yml
          parameters:
            azureSubscription: ${{ parameters.azureSubscription }}
        - script: |
            terraform init -no-color -input=false ${{ parameters.backendArg }}
            terraform destroy -no-color -input=false -auto-approve -var-file=${{ parameters.varFile }}
          displayName: Terraform Destroy
          workingDirectory: ${{ parameters.rootFolder }}
