parameters:
  additionalVars: ''
  varFile: ''
  backendArg: ''
  azureSubscription: '00c93c32-5bf8-426d-8e40-1909df2d6dd9'
  rootFolder: ''
  artifactName: 'plan'
  pool: 
    name: 'ubuntu'
jobs:
- job: plan
  displayName: Terraform Plan
  pool: ${{ parameters.pool }}
  steps:
  - template: get-tf-credentials.steps.yml
    parameters:
      azureSubscription: ${{ parameters.azureSubscription }}
  - script: |
      terraform init -input=false ${{ parameters.backendArg }}
      terraform plan -input=false -var-file=${{ parameters.varFile }} ${{ parameters.additionalVars }} -out="$(Build.ArtifactStagingDirectory)/out.plan"
    workingDirectory: ${{ parameters.rootFolder }}
    displayName: Terraform Plan
  - publish: $(Build.ArtifactStagingDirectory)/out.plan
    artifact: ${{ parameters.artifactName }}
